### ISSUE TITLE
Exercise 1-e

### ISSUE THREAD

**Issue by khionech** [CMU-MS-DAS-Modern-Programming-Mini/fall2022-final-project#1]
I have problems with Exercise 1-e:

I got an error when using `compute_xxh128sum` but did not know how to fix it:

> <img width="761" alt="image" src="https://user-images.githubusercontent.com/112643201/196059739-2ca58b8c-bb34-4ecb-9592-5e183ffcafeb.png">

What I have done:

1. I created a txt file called tmp.txt in the current working directory and I found that `compute_xxh128sum` could work on it.

> <img width="497" alt="image" src="https://user-images.githubusercontent.com/112643201/196060337-419253a6-5abb-405e-83a1-203cd7d1141f.png">

2. I checked if the file exists by using `cat` command in the terminal. I believed that the file does exist so I had no idea why `compute_xxh128sum` could not work on it.

> <img width="559" alt="image" src="https://user-images.githubusercontent.com/112643201/196060159-f3090255-a278-42b7-8bb5-180bb9b4153b.png">

Could you give me some hints on fixing it? Thank you!

**Comment by icaoberg** [comment]
@khionech so of the files do not have the write permissions to compute the checksum

```
dr-xr-xr-x 113 bil bil   18944 Feb 24  2021 ..
-r--r--r--   1 bil bil     534 Dec  5  2019 190895.json
-r--r--r--   1 bil bil     693 Dec  5  2019 190895-metainfo.txt
dr-xr-xr-x   5 bil bil   11776 Dec  5  2019 .
-r--r--r--   1 bil bil 1071128 Dec  4  2019 xxhash_dat_mouseID_19022522-190895
dr-xr-xr-x   2 bil bil   16896 Dec  4  2019 CH1_0.35_100um
dr-xr-xr-x   2 bil bil   16896 Dec  4  2019 CH1_3.5_100um
dr-xr-xr-x   3 bil bil 1573376 Jun 29  2019 CH1
```

If you are unable to compute the checksum then I would suggest you populate this particular cell as `None`.

**Comment by icaoberg** [comment]
@khionech this issue has been fixed by updating the `xxh128` script.
